---
- name: setup dev server
  hosts: all
  vars:
     dbame: "{{ dbname }}"
  tasks:
    - name: install dependencies via apt
      apt:
          name: "{{ packages }}"
      vars:
        packages:
        - mariadb-server
        - python3-pip
        - vim
        - python-mysqldb
        - libmariadbclient-dev
      become: true

    - name: install dependencies via pip
      pip:
        name: "{{ packages }}"
        state: present
        executable: pip3
      vars:
        packages:
        - django==2.0.1
        - mysqlclient

    - name: start mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes
      become: true

    - name: Create a new database with name "{{ dbname }}"
      mysql_db:
        name: "{{ dbname }}"
        state: present
        login_user: root
      become: true

    - name: Removes all anonymous user accounts
      mysql_user:
          name: ''
          host_all: yes
          state: absent
          login_user: root
      become: true

    - name: Create database user with name {{ dbname }} and password {{ dbname }} with all database privileges
      mysql_user:
        name: "{{ dbname }}"
        password: "{{ dbname }}"
        priv: "*.*:ALL"
        state: present
        login_user: root
      become: true

    - name: Add line to .bashrc to change the working directory to /vagrant upon ssh login
      blockinfile:
        dest: /home/vagrant/.bashrc
        block: |
          cd /vagrant
      become: true

    - name: add /home/vagrant/.local/bin/ to the vagrant user's PATH
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: 'PATH=$PATH:/home/vagrant/.local/bin'

    - name: Running django-admin to create new project
      shell: python3 /home/vagrant/.local/bin/django-admin startproject {{ dbname }}
      args:
        chdir: /vagrant
        creates: '{{ dbname }}/manage.py'
      become: true
      become_user: vagrant

    - name: remove old django DATABASE configuration settings
      template:
        src: settings.py.j2
        dest: /vagrant/{{ dbname }}/{{ dbname }}/settings.py
