---
- name: setup dev server
  hosts: all
  vars:
     dbame: "{{dbname}}"
  tasks:
    - name: install mariadb-server
      apt:
        name: mariadb-server
        state: present
      become: true

    - name: install python3-pip
      apt:
        name: python3-pip
        state: present
      become:  true

    - name: install vim
      apt:
        name: vim
        state: present
      become:  true

    - name: install python-mysqldb
      apt:
        name: python-mysqldb
        state: present
      become:  true

    - name: install libmariadbclient-dev
      apt:
        name: libmariadbclient-dev
        state: present
      become: true

    - name: install django
      pip:
        name: "django==2.0.1"
        state: present
        executable: pip3

    - name: install mysqlclient dependency
      pip:
        name: "mysqlclient"
        state: present
        executable: pip3

    - name: start mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes
      become: true

    - name: Create a new database with name "{{dbname}}"
      mysql_db:
        name: "{{dbname}}"
        state: present
        login_user: root
      become: true

    - name: Removes all anonymous user accounts
      mysql_user:
          name: ''
          host_all: yes
          state: absent
          login_user: root
      become: true

    - name: Create database user with name "{{dbname}}" and password "{{dbname}}" with all database privileges
      mysql_user:
        name: "{{dbname}}"
        password: "{{dbname}}"
        priv: "{{dbname}}.*:ALL"
        state: present
        login_user: root
      become: true

    - name: Add line to .bashrc to change the working directory to /vagrant upon ssh login
      blockinfile:
        dest: /home/vagrant/.bashrc
        block: |
          cd /vagrant
      become: true

    - name: add /home/vagrant/.local/bin/ to the vagrant user's PATH
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: 'PATH=$PATH:/home/vagrant/.local/bin'

    - name: Running django-admin to create new project
      shell: 'python3 /home/vagrant/.local/bin/django-admin startproject {{dbname}}'
      args:
        chdir: /vagrant
        creates: '{{dbname}}/manage.py'
      become: true
      become_user: vagrant
