---
- name: setup dev server
  hosts: all 
  vars:
     dbame: "{{dbname}}"
  tasks:      
    - name: install mariadb-server
      apt:
        name: mariadb-server
        state: present
      become: true

    - name: install python3-pip
      apt:
        name: python3-pip
        state: present
      become:  true

    - name: install python-mysqldb
      apt:
        name: python-mysqldb
        state: present
      become:  true
   
    - name: install libmariadbclient-dev 
      apt:
        name: libmariadbclient-dev
        state: present        
      become: true

    - name: install django and mysqlclient dependency
      pip:
        name: "django==2.0.1 mysqlclient"
        state: present
        executable: pip3

    - name: start mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes
      become: true

    - name: Create a new database with name "{{dbname}}"
      mysql_db:
        name: "{{dbname}}"
        state: present    
        login_user: root
      become: true
    
    - name: Removes all anonymous user accounts
      mysql_user:
          name: ''
          host_all: yes
          state: absent
          login_user: root
      become: true

    - name: Create database user with name "{{dbname}}" and password "{{dbname}}" with all database privileges
      mysql_user:
        name: "{{dbname}}"
        password: "{{dbname}}"
        priv: "{{dbname}}.*:ALL"
        state: present
        login_user: root
      become: true

    - name: Add line to .bashrc to change the working directory to /vagrant upon ssh login
      blockinfile:
        dest: /home/vagrant/.bashrc
        block: |
          cd /vagrant    
      become: true
